name: CMake-32

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        repository: Z3Prover/z3
  
    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DZ3_BUILD_LIBZ3_SHARED=OFF -A Win32
        cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
        
    - name: Copy SDK
      run: |
          mkdir build\include
          copy src\api\*.h build\include
          mkdir build\lib
          copy build\Release\*.* build\lib
        
    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: libz3-32
        path: |
          build/include/*
          build/lib/*

        
