name: CMake-32

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        repository: gmh5225/z3
        ref: master
  
    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DZ3_BUILD_LIBZ3_SHARED=OFF -DZ3_BUILD_LIBZ3_MSVC_STATIC=ON -A Win32
        cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
        
    - name: Copy SDK
      run: |
          mkdir build\include
          copy src\api\*.h build\include
          copy src\api\c++\*.h build\include
          copy src\util\*.h build\include
          mkdir build\lib
          copy build\Release\*.* build\lib
        
    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: libz3-32-${{ github.run_number }}
        path: |
          build/include/*
          build/lib/*
          
    - name: Compress artifacts
      uses: vimtor/action-zip@26a249fb00d43ca98dad77a4b3838025fc226aa1 # v1.1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: |
         build64/include/*.*
         build64/lib/*.*
        dest: libz3-win32.zip

    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: libz3-win32.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
